packages:
  - apps/*
  - packages/*

catalog:
  '@hono/node-server': 1.19.9
  '@tailwindcss/vite': 4.2.0
  '@types/better-sqlite3': 7.6.13
  '@types/node': 25.3.0
  better-sqlite3: 12.6.2
  drizzle-kit: 0.31.9
  drizzle-orm: 0.45.1
  hono: 4.11.10
  nuxt: 4.3.1
  tailwindcss: 4.2.0
  tsx: 4.21.0
  typescript: 5.9.3
  vue: 3.5.28
  vue-router: 5.0.2
  vue-tsc: 3.2.4
  zod: 4.3.6

catalogMode: prefer

cleanupUnusedCatalogs: true

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - esbuild

injectWorkspacePackages: true

onlyBuiltDependencies:
  - better-sqlite3

syncInjectedDepsAfterScripts:
  - build

# Required for Nitro's server-externalized packages (e.g. unhead) to resolve their
# transitive deps (e.g. hookable) at runtime in the Docker deployment.
shamefullyHoist: true